<?php
  /* URL configurations. */
  define("AR_REPORT_URL", AR_URL . "report/");
  define("AR_REPORT_MONTHLY_SALES_URL", AR_REPORT_URL . "monthly-sales/");
  define("AR_REPORT_CLIENT_URL", AR_REPORT_URL . "client/");
  define("AR_REPORT_CLIENT_STATISTICS_URL", AR_REPORT_CLIENT_URL . "statistics/");
  define("AR_REPORT_CLIENT_OUTSTANDING_URL", AR_REPORT_CLIENT_URL . "outstanding/");
  define("AR_REPORT_CLIENT_OUTSTANDING_DETAIL_URL", AR_REPORT_CLIENT_OUTSTANDING_URL . "detail/");
  define("AR_REPORT_CLIENT_STATEMENT_URL", AR_REPORT_CLIENT_URL . "statement/");
  define("AR_REPORT_CLIENT_STATEMENT_PRINTOUT_URL", AR_REPORT_CLIENT_STATEMENT_URL . "printout/");
  define("AR_REPORT_DAILY_REPORT_URL", AR_REPORT_URL . "daily-report/");

  /* Title configurations. */
  define("AR_REPORT_TITLE", "(E) Management Report");
  define("AR_REPORT_MONTHLY_SALES_TITLE", "(E1) Monthly Sales");
  define("AR_REPORT_CLIENT_STATISTICS_TITLE", "(E2) Customer Statistics");
  define("AR_REPORT_CLIENT_OUTSTANDING_TITLE", "(E3) Customer Outstanding");
  define("AR_REPORT_CLIENT_OUTSTANDING_SUMMARY_TITLE", "(E3a) Customer Outstanding Summary By Client");
  define("AR_REPORT_CLIENT_OUTSTANDING_DETAIL_TITLE", "(E3b) Customer Outstanding Detail By Client By Maturity Date");
  define("AR_REPORT_CLIENT_STATEMENT_TITLE", "(E4) Customer Statements");
  define("AR_REPORT_CLIENT_STATEMENT_PRINTOUT_TITLE", "Customer Statement（月結單）");
  define("AR_REPORT_DAILY_REPORT_TITLE", "(E5) Daily Report");

  $AR_REPORT_MODULE = array(
    AR_REPORT_MONTHLY_SALES_TITLE       => AR_REPORT_MONTHLY_SALES_URL,
    AR_REPORT_CLIENT_STATISTICS_TITLE   => AR_REPORT_CLIENT_STATISTICS_URL,
    AR_REPORT_CLIENT_OUTSTANDING_TITLE  => array(
      AR_REPORT_CLIENT_OUTSTANDING_SUMMARY_TITLE  => AR_REPORT_CLIENT_OUTSTANDING_URL,
      AR_REPORT_CLIENT_OUTSTANDING_DETAIL_TITLE   => AR_REPORT_CLIENT_OUTSTANDING_DETAIL_URL,
    ),
    AR_REPORT_CLIENT_STATEMENT_TITLE    => AR_REPORT_CLIENT_STATEMENT_URL,
    AR_REPORT_DAILY_REPORT_TITLE        => AR_REPORT_DAILY_REPORT_URL
  );
?>
