<?php
  /* URL configurations. */
  define("REPORT_URL", MENU_URL . "report/");
  define("REPORT_HISTORY_LOG_URL", REPORT_URL . "history-log/");
  define("REPORT_STOCK_TAKE_URL", REPORT_URL . "stock-take/");
  define("REPORT_STOCK_TAKE_WAREHOUSE_URL", REPORT_STOCK_TAKE_URL . "warehouse/");
  define("REPORT_STOCK_TAKE_WAREHOUSE_DETAIL_URL", REPORT_STOCK_TAKE_WAREHOUSE_URL . "detail/");
  define("REPORT_STOCK_TAKE_BRAND_URL", REPORT_STOCK_TAKE_URL . "brand/");
  define("REPORT_STOCK_TAKE_BRAND_DETAIL_URL", REPORT_STOCK_TAKE_BRAND_URL . "detail/");
  define("REPORT_STOCK_TAKE_MODEL_URL", REPORT_STOCK_TAKE_URL . "model/");
  define("REPORT_STOCK_TAKE_MODEL_DETAIL_URL", REPORT_STOCK_TAKE_MODEL_URL . "detail/");
  define("REPORT_STOCK_IN_URL", REPORT_URL . "stock-in/");
  define("REPORT_STOCK_IN_DATE_URL", REPORT_STOCK_IN_URL . "date/");


  /* Title configurations. */
  define("REPORT_TITLE", "(G) Management Report");
  define("REPORT_HISTORY_LOG_TITLE", "(G1) History Log");
  define("REPORT_STOCK_TAKE_TITLE", "(G7) Stock Take");
  define("REPORT_STOCK_TAKE_WAREHOUSE_TITLE", "(G7a) Stock Take By Location");
  define("REPORT_STOCK_TAKE_WAREHOUSE_DETAIL_TITLE", "(G7b) Stock Take Detail By Location");
  define("REPORT_STOCK_TAKE_BRAND_TITLE", "(G7c) Stock Take By Brand");
  define("REPORT_STOCK_TAKE_BRAND_DETAIL_TITLE", "(G7d) Stock Take Detail By Brand");
  define("REPORT_STOCK_TAKE_MODEL_TITLE", "(G7e) Stock Take By Model");
  define("REPORT_STOCK_TAKE_MODEL_DETAIL_TITLE", "(G7f) Stock Take Detail By Model");
  define("REPORT_STOCK_IN_TITLE", "(G8) Stock In");
  define("REPORT_STOCK_IN_DATE_TITLE", "(G8a) Stock In Report By Date");

  $REPORT_MODULE = array(
    REPORT_HISTORY_LOG_TITLE => REPORT_HISTORY_LOG_URL,
    REPORT_STOCK_TAKE_TITLE => array(
      REPORT_STOCK_TAKE_WAREHOUSE_TITLE => REPORT_STOCK_TAKE_WAREHOUSE_URL,
      REPORT_STOCK_TAKE_WAREHOUSE_DETAIL_TITLE => REPORT_STOCK_TAKE_WAREHOUSE_DETAIL_URL,
      REPORT_STOCK_TAKE_BRAND_TITLE => REPORT_STOCK_TAKE_BRAND_URL,
      REPORT_STOCK_TAKE_BRAND_DETAIL_TITLE => REPORT_STOCK_TAKE_BRAND_DETAIL_URL,
      // REPORT_STOCK_TAKE_MODEL_TITLE => REPORT_STOCK_TAKE_MODEL_URL,
      // REPORT_STOCK_TAKE_MODEL_DETAIL_TITLE => REPORT_STOCK_TAKE_MODEL_DETAIL_URL
    ),
    REPORT_STOCK_IN_TITLE => array(
      REPORT_STOCK_IN_DATE_TITLE => REPORT_STOCK_IN_DATE_URL
    )
  );
?>
