<?php
  /* URL configurations. */
  define("SALES_URL", MENU_URL . "sales/");
  define("SALES_ORDER_URL", SALES_URL . "sales-order/");
  define("SALES_ORDER_PRINTOUT_URL", SALES_ORDER_URL . "printout/");
  define("SALES_ORDER_INTERNAL_PRINTOUT_URL", SALES_ORDER_URL . "internal-printout/");
  define("SALES_ORDER_SAVED_URL", SALES_ORDER_URL . "saved/");
  define("SALES_ORDER_POSTED_URL", SALES_ORDER_URL . "posted/");
  define("SALES_ORDER_PRIORITY_URL", SALES_ORDER_URL . "priority/");

  define("SALES_OUTSTANDING_REPORT_URL", SALES_URL . "outstanding-report/");
  define("SALES_REPORT_CUSTOMER_SUMMARY_URL", SALES_OUTSTANDING_REPORT_URL . "client/");
  define("SALES_REPORT_CUSTOMER_DETAIL_URL", SALES_REPORT_CUSTOMER_SUMMARY_URL . "detail/");
  define("SALES_REPORT_BRAND_SUMMARY_URL", SALES_OUTSTANDING_REPORT_URL . "brand/");
  define("SALES_REPORT_BRAND_DETAIL_URL", SALES_REPORT_BRAND_SUMMARY_URL . "detail/");
  define("SALES_REPORT_MODEL_SUMMARY_URL", SALES_OUTSTANDING_REPORT_URL . "model/");
  define("SALES_REPORT_MODEL_DETAIL_URL", SALES_REPORT_MODEL_SUMMARY_URL . "detail/");

  define("SALES_PL_REPORT_URL", SALES_URL . "pl-report/");
  define("SALES_PL_REPORT_MODEL_SUMMARY_URL", SALES_PL_REPORT_URL . "model/");
  define("SALES_PL_REPORT_MODEL_DETAIL_URL", SALES_PL_REPORT_MODEL_SUMMARY_URL . "detail/");

  define("SALES_ALLOTMENT_URL", SALES_URL . "allotment/");
  define("SALES_ALLOTMENT_INCOMING_URL", SALES_ALLOTMENT_URL . "incoming/");
  define("SALES_ALLOTMENT_STOCK_URL", SALES_ALLOTMENT_URL . "stock/");

  define("SALES_ALLOTMENT_REPORT_URL", SALES_URL . "allotment-report/");
  define("SALES_ALLOTMENT_REPORT_CUSTOMER_URL", SALES_ALLOTMENT_REPORT_URL . "client/");

  define("SALES_DELIVERY_ORDER_URL", SALES_URL . "delivery-order/");
  define("SALES_DELIVERY_ORDER_PRINTOUT_URL", SALES_DELIVERY_ORDER_URL . "printout/");
  define("SALES_DELIVERY_ORDER_INTERNAL_PRINTOUT_URL", SALES_DELIVERY_ORDER_URL . "internal-printout/");
  define("SALES_DELIVERY_ORDER_INVOICE_URL", SALES_DELIVERY_ORDER_URL . "invoice/");
  define("SALES_DELIVERY_ORDER_SAVED_URL", SALES_DELIVERY_ORDER_URL . "saved/");
  define("SALES_DELIVERY_ORDER_POSTED_URL", SALES_DELIVERY_ORDER_URL . "posted/");


  /* Title configurations. */
  define("SALES_TITLE", "(F) Sales");
  define("SALES_ORDER_PRINTOUT_TITLE", "Sales Order");
  define("SALES_ORDER_INTERNAL_PRINTOUT_TITLE", "Sales Order (Internal)");
  define("SALES_ORDER_TITLE", "(F1) Sales Order");
  define("SALES_ORDER_CREATE_TITLE", "(F1a) Create Sales Order");
  define("SALES_ORDER_SAVED_TITLE", "(F1b) Saved Sales Orders");
  define("SALES_ORDER_POSTED_TITLE", "(F1c) Posted Sales Orders");
  define("SALES_ORDER_PRIORITY_TITLE", "(F1d) Sales Order Priorities");

  define("SALES_OUTSTANDING_REPORT_TITLE", "(F2) Outstanding Report");
  define("SALES_REPORT_CUSTOMER_SUMMARY_TITLE", "(F2a) Sales Summary By Client");
  define("SALES_REPORT_CUSTOMER_DETAIL_TITLE", "(F2b) Sales Detail By Client");
  define("SALES_REPORT_BRAND_SUMMARY_TITLE", "(F2c) Sales Summary By Brand");
  define("SALES_REPORT_BRAND_DETAIL_TITLE", "(F2d) Sales Detail By Brand");
  define("SALES_REPORT_MODEL_SUMMARY_TITLE", "(F2e) Sales Summary By Model");
  define("SALES_REPORT_MODEL_DETAIL_TITLE", "(F2f) Sales Detail By Model");

  define("SALES_PL_REPORT_TITLE", "(F3) P/L Analysis Report");
  define("SALES_PL_REPORT_MODEL_SUMMARY_TITLE", "(F3c) Sales P/L Summary By Model");
  define("SALES_PL_REPORT_MODEL_DETAIL_TITLE", "(F3d) Sales P/L Detail By Model");

  define("SALES_ALLOTMENT_TITLE", "(F4) Allotment");
  define("SALES_ALLOTMENT_INCOMING_TITLE", "(F4a) Incoming Allotment");
  define("SALES_ALLOTMENT_STOCK_TITLE", "(F4b) Stock Allotment");

  define("SALES_ALLOTMENT_REPORT_TITLE", "(F5) Allotment Report");
  define("SALES_ALLOTMENT_REPORT_CUSTOMER_TITLE", "(F5a) Allotment Report By Client");

  define("SALES_DELIVERY_ORDER_TITLE", "(F6) Delivery Order");
  define("SALES_DELIVERY_ORDER_PRINTOUT_TITLE", "Delivery Order");
  define("SALES_DELIVERY_ORDER_INTERNAL_PRINTOUT_TITLE", "Delivery Order (Internal)");
  define("SALES_DELIVERY_ORDER_SAVED_TITLE", "(F6a) Saved Delivery Orders");
  define("SALES_DELIVERY_ORDER_POSTED_TITLE", "(F6b) Posted Delivery Orders");

  $SALES_MODULE = array(
    SALES_ORDER_TITLE => array(
      SALES_ORDER_CREATE_TITLE              => SALES_ORDER_URL,
      SALES_ORDER_SAVED_TITLE               => SALES_ORDER_SAVED_URL,
      SALES_ORDER_POSTED_TITLE              => SALES_ORDER_POSTED_URL,
      SALES_ORDER_PRIORITY_TITLE            => SALES_ORDER_PRIORITY_URL
    ),
    SALES_OUTSTANDING_REPORT_TITLE => array(
      SALES_REPORT_CUSTOMER_SUMMARY_TITLE   => SALES_REPORT_CUSTOMER_SUMMARY_URL,
      SALES_REPORT_CUSTOMER_DETAIL_TITLE    => SALES_REPORT_CUSTOMER_DETAIL_URL,
      SALES_REPORT_BRAND_SUMMARY_TITLE      => SALES_REPORT_BRAND_SUMMARY_URL,
      SALES_REPORT_BRAND_DETAIL_TITLE       => SALES_REPORT_BRAND_DETAIL_URL,
      SALES_REPORT_MODEL_SUMMARY_TITLE      => SALES_REPORT_MODEL_SUMMARY_URL,
      SALES_REPORT_MODEL_DETAIL_TITLE       => SALES_REPORT_MODEL_DETAIL_URL
    ),
    SALES_PL_REPORT_TITLE => array(
      SALES_PL_REPORT_MODEL_SUMMARY_TITLE   => SALES_PL_REPORT_MODEL_SUMMARY_URL,
      SALES_PL_REPORT_MODEL_DETAIL_TITLE    => SALES_PL_REPORT_MODEL_DETAIL_URL
    ),
    SALES_ALLOTMENT_TITLE => array(
      SALES_ALLOTMENT_INCOMING_TITLE        => SALES_ALLOTMENT_INCOMING_URL,
      SALES_ALLOTMENT_STOCK_TITLE           => SALES_ALLOTMENT_STOCK_URL
    ),
    SALES_ALLOTMENT_REPORT_TITLE => array(
      SALES_ALLOTMENT_REPORT_CUSTOMER_TITLE => SALES_ALLOTMENT_REPORT_CUSTOMER_URL
    ),
    SALES_DELIVERY_ORDER_TITLE => array(
      SALES_DELIVERY_ORDER_SAVED_TITLE      => SALES_DELIVERY_ORDER_SAVED_URL,
      SALES_DELIVERY_ORDER_POSTED_TITLE     => SALES_DELIVERY_ORDER_POSTED_URL
    )
  );
?>
